### ISSUE TITLE
DeprecationWarning: Tapable.apply is deprecated.

### ISSUE THREAD

**Issue by maxlapides** [developit/workerize-loader#28]
On my *Webpack 4* build, I'm getting this warning:

```
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
```

If I run my Webpack build like:

```
node --trace-deprecation ./node_modules/.bin/webpack-dev-server
```

I can see that this warning is coming from workerize-loader:

```
(node:31068) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at Object.loader.pitch (/Users/me/my-app/node_modules/workerize-loader/dist/index.js:29:21)
    at LOADER_EXECUTION (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at /Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:175:3
    at loadLoader (/Users/me/my-app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/me/my-app/node_modules/webpack/lib/NormalModule.js:219:3)
    at NormalModule.build (/Users/me/my-app/node_modules/webpack/lib/NormalModule.js:337:15)
    at Compilation.buildModule (/Users/me/my-app/node_modules/webpack/lib/Compilation.js:346:10)
(node:31068) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at Object.loader.pitch (/Users/me/my-app/node_modules/workerize-loader/dist/index.js:35:21)
    at LOADER_EXECUTION (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at /Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:175:3
    at loadLoader (/Users/me/my-app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/me/my-app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/me/my-app/node_modules/webpack/lib/NormalModule.js:219:3)
    at NormalModule.build (/Users/me/my-app/node_modules/webpack/lib/NormalModule.js:337:15)
    at Compilation.buildModule (/Users/me/my-app/node_modules/webpack/lib/Compilation.js:346:10)
```

**Comment by shellscape** [comment]
That stems from this line here: https://github.com/developit/workerize-loader/blob/41cff66a0dae51bf873b81823cf02d82d5af2d5e/src/index.js#L44

That needs to be changed to `worker.compiler.hooks.compilation.tap` for webpack 4.

ping @developit

**Comment by developit** [comment]
I'd love someone to PR that change if anyone has time! :)

It'll need a little feature test:

```js
if (worker.compiler.hooks) {
  worker.compiler.hooks.compilation.tap('workerize-loader', handleCompilation);
}
else {
  worker.compiler.plugin('compilation', handleCompilation);
}

function handleCompilation(compilation, data) {
    // existing callback code
```
